#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"C-p")      while read file; do realpath "$file" | xclip -sel c -r; done ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file" && notify-send "🖼️" "Image copied to clipboard"; done ;;
"C-d")      while read file; do rm "$file"; done ;;
"C-l")	    while read file; do setlockbg "$file"; done ;;
"C-L")	    while read file; do setlockbg --no-blur "$file"; done ;;
"C-o")	    while read file; do 0x0 "$file"; done ;;
"C-e")      while read file; do sxiv-handler "$file"; done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-b")	    while read file; do setbg "$file"; done ;;
"C-m")	    while read file; do sxiv-move-img "$file"; done ;;
"C-w")	    while read file; do setwal "$file"; done ;;
"C-r")      while read file; do convert "$file" -channel RGB -negate "$file"; done ;;
# "C-r")      while read file; do rawtherapee "$file" & done ;;
"C-comma")  rotate 270 ;;
"C-period") rotate  90 ;;
"C-slash")  rotate 180 ;;
esac

