--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/samisthefbi/Wallpapers/__souryuu_asuka_langley_ayanami_rei_ikari_shinji_nagisa_kaworu_makinami_mari_illustrious_and_8_more_neon_genesis_evangelion_and_2_more_drawn_by_yuko666__1ee7de908ef9a4551d4f51456f51df82.jpg"

-- Special
background="#1b1818"
foreground="#ede6de"
cursor="#ede6de"

-- Colors
color0="#1b1818"
color1="#D69E60"
color2="#61909E"
color3="#AE9F92"
color4="#D3B29D"
color5="#EACFB2"
color6="#BBBBC2"
color7="#ede6de"
color8="#a5a19b"
color9="#D69E60"
color10="#61909E"
color11="#AE9F92"
color12="#D3B29D"
color13="#EACFB2"
color14="#BBBBC2"
color15="#ede6de"
