# Shell variables
# Generated by 'wal'
wallpaper='/home/samisthefbi/Wallpapers/__souryuu_asuka_langley_ayanami_rei_ikari_shinji_nagisa_kaworu_makinami_mari_illustrious_and_8_more_neon_genesis_evangelion_and_2_more_drawn_by_yuko666__1ee7de908ef9a4551d4f51456f51df82.jpg'

# Special
background='#1b1818'
foreground='#ede6de'
cursor='#ede6de'

# Colors
color0='#1b1818'
color1='#D69E60'
color2='#61909E'
color3='#AE9F92'
color4='#D3B29D'
color5='#EACFB2'
color6='#BBBBC2'
color7='#ede6de'
color8='#a5a19b'
color9='#D69E60'
color10='#61909E'
color11='#AE9F92'
color12='#D3B29D'
color13='#EACFB2'
color14='#BBBBC2'
color15='#ede6de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
