--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/samisthefbi/Wallpapers/__komeiji_koishi_touhou_drawn_by_noumin_joemanyodw__38a2db300044a7744147264651dc70aa.png"

-- Special
background="#09111c"
foreground="#a9e3c4"
cursor="#a9e3c4"

-- Colors
color0="#09111c"
color1="#A86B54"
color2="#4B8975"
color3="#C6A06E"
color4="#1F7C81"
color5="#298A86"
color6="#5E9889"
color7="#a9e3c4"
color8="#769e89"
color9="#A86B54"
color10="#4B8975"
color11="#C6A06E"
color12="#1F7C81"
color13="#298A86"
color14="#5E9889"
color15="#a9e3c4"
