# Shell variables
# Generated by 'wal'
wallpaper='/home/samisthefbi/Wallpapers/__komeiji_koishi_touhou_drawn_by_noumin_joemanyodw__38a2db300044a7744147264651dc70aa.png'

# Special
background='#09111c'
foreground='#a9e3c4'
cursor='#a9e3c4'

# Colors
color0='#09111c'
color1='#A86B54'
color2='#4B8975'
color3='#C6A06E'
color4='#1F7C81'
color5='#298A86'
color6='#5E9889'
color7='#a9e3c4'
color8='#769e89'
color9='#A86B54'
color10='#4B8975'
color11='#C6A06E'
color12='#1F7C81'
color13='#298A86'
color14='#5E9889'
color15='#a9e3c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
