#!/bin/bash

source "`ueberzug library`"

COVER="$HOME/.config/ncmpcpp/albumarts/tmp.jpg"

function add_cover {
  ImageLayer::add [identifier]="img" [x]="2" [y]="7" [max_width]="60" [max_width]="60" [path]="$COVER"
}

ImageLayer 0< <(
if [ ! -f "$COVER" ]; then
  cp "$HOME/.config/ncmpcpp/albumarts/default_cover.jpg" "$COVER"
fi
add_cover
sleep 5
#rerender image when changed
#while inotifywait -q -q -e close_write "$COVER"; do
#  add_cover
#done
)

